version: '3'
services:
  behavior:
    build:
      context: ../..
      dockerfile: ././build/package/behavior-dev/Dockerfile
    volumes:
      - ../../log/web:/go/src/a2os/behavior/log/
      - ../../conf:/go/src/a2os/behavior/conf/
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "9005:8080"
    networks:
      - behavior-app-net
    # depends_on:
    #   - db
#      - redis
    restart: always

  # db:
  #   environment:
  #     - TZ=Asia/Shanghai
  #     - MYSQL_ROOT_PASSWORD=behavior
  #     - MYSQL_DATABASE=behavior
  #   image: mariadb:10.3
  #   volumes:
  #     - ../../data-dev/mariadb:/var/lib/mysql
  #     - ../../conf/mariadb:/etc/mysql/conf.d
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - behavior-app-net
  #   restart: on-failure

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "10000:8080"
  #   networks:
  #     - behavior-app-net

#  redis:
#    image: redis:5.0.3-alpine
#    environment:
#      - TZ=Asia/Shanghai
#    volumes:
#      - ../../conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
#      - ../../data-dev/redis:/data # for redis persistent storage
#    entrypoint: redis-server /usr/local/etc/redis/redis.conf
#    ports:
#      - "6379:6379"
#    networks:
#      - behavior-app-net
#    restart: on-failure

networks:
  behavior-app-net:
